### ISSUE TITLE
Beta crashes after scanning directories

### ISSUE THREAD

**Issue by rlach** [rlach/gameManagement#19]
```
events.js:174
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token B in JSON at position 0
    at JSON.parse (<anonymous>)
    at DestroyableTransform.module.exports.vbsOutputTransform [as _transform] (D:\snapshot\gameManagement\node_modules\regedit\lib\helper.js:51:18)
    at DestroyableTransform.Transform._read (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
    at doWrite (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
    at writeOrBuffer (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
    at StreamSlicer.ondata (_stream_readable.js:689:20)
    at StreamSlicer.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at StreamSlicer.Readable.push (_stream_readable.js:220:10)
    at StreamSlicer.Transform.push (_stream_transform.js:151:32)
    at StreamSlicer._separatorFlush (D:\snapshot\gameManagement\node_modules\stream-slicer\index.js:63:7)
    at StreamSlicer._transform (D:\snapshot\gameManagement\node_modules\stream-slicer\index.js:33:8)
    at StreamSlicer.Transform._read (_stream_transform.js:190:10)
    at StreamSlicer.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at StreamSlicer.Writable.write (_stream_writable.js:294:11)
    at Socket.ondata (_stream_readable.js:689:20)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
Emitted 'error' event at:
    at DestroyableTransform.onerror (_stream_readable.js:713:12)
    at DestroyableTransform.emit (events.js:189:13)
    at onwriteError (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:250:10)
    at onwrite (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:268:5)
    at WritableState.onwrite (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:106:5)
    at afterTransform (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:104:5)
    at TransformState.afterTransform (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:79:12)
    at DestroyableTransform.module.exports.vbsOutputTransform [as _transform] (D:\snapshot\gameManagement\node_modules\regedit\lib\helper.js:53:10)
    at DestroyableTransform.Transform._read (D:\snapshot\gameManagement\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:189:13)
```

**Comment by rlach** [comment]
For now the error is handled, not sure why it happens yet

**Comment by rlach** [comment]
Fixed in newest MR, but caused new issue
