### ISSUE TITLE
 Failure in main process TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by Roshri** [rlach/gameManagement#24]
Thanks for your hard work in this program, it really saved me lots of time.

When running "get possible codes in unsorted directory" it sometimes crashes even when the folder name correctly matches an entry in vndb, for instance. Then it gets stalled on that folder instead of skipping it.

> `Getting game codes [Imouto Ijime] [████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 10% | ETA: 3m55s | Duration: 30s | 5/5121:20:49.058Z ERROR app:
  Failure in main process TypeError: Cannot read property '0' of null
      at Element.query.filter.map (D:\snapshot\gameManagement\src\parsers\dmm.js:0:0)
      at D:\snapshot\gameManagement\node_modules\cheerio\lib\api\traversing.js:306:18
      at D:\snapshot\gameManagement\node_modules\lodash\_baseReduce.js:18:9
      at module.exports (D:\snapshot\gameManagement\node_modules\lodash\_createBaseEach.js:24:11)
      at baseReduce (D:\snapshot\gameManagement\node_modules\lodash\_baseReduce.js:15:3)
      at Object.reduce (D:\snapshot\gameManagement\node_modules\lodash\reduce.js:48:10)
      at initialize.exports.map (D:\snapshot\gameManagement\node_modules\cheerio\lib\api\traversing.js:305:23)
      at getProResults (D:\snapshot\gameManagement\src\parsers\dmm.js:0:0)`

**Comment by rlach** [comment]
This is now fixed and merged. Will also be part of 1.0.0-beta.2 with few other fixes.
